### ISSUE TITLE
Connection through TOR not working

### ISSUE THREAD

**Issue by derWahnsinn** [qsocket/qs-netcat#1]
Hello,

I'm currently testing qsocket (qs-netcat) and can't connect to the client through TOR.
-T switch brings the following error:
`[ERROR] invalid knock response`

I also tried to specify the proxy through the -x switch, with the same result.

Thanks!

**Comment by EgeBalci** [comment]
Thanks for reporting.

This issue is due to the Cloudflare's restrictions to connections coming from TOR network. It should be fixed with the latest [v0.0.7-beta](https://github.com/qsocket/qs-netcat/releases/tag/v0.0.7-beta) release. Now qsocket is using its own `onion` address for connections over TOR effectively bypassing CF.
